obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.18
footprint: [[0.15, 0.12], [0.15, -0.12], [-0.15, -0.12], [-0.15, 0.12]]
inflation_radius: 0.3
observation_sources: scan
scan:
  sensor_frame: limo0/laser_link
  data_type: LaserScan
  topic: /limo0/scan
  marking: true
  clearing: true

