DWAPlannerROS:
  # Robot configuration
  holonomic_robot: false
  max_vel_x: 1.
  min_vel_x: 0.0
  acc_lim_x: 1.5
 
  max_vel_theta: 1.6
  min_in_place_vel_theta: 0.0
  max_vel_theta: 2.0
  track_unknown_space: true


